# Generated by Django 3.1.7 on 2021-03-16 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomreservation',
            old_name='ower',
            new_name='owner',
        ),
    ]
