# Generated by Django 3.1.7 on 2021-03-16 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_auto_20210315_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Bath'), (2, 'Bath and HairCut')])),
            ],
        ),
        migrations.AlterField(
            model_name='roomreservation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_reservation', to='reservation.room'),
        ),
    ]
