# Generated by Django 3.1.7 on 2021-03-16 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0002_auto_20210314_2120'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservation', '0003_auto_20210316_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroomSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_period', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='GroomReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Confirm'), (2, 'Cancel')], default=1)),
                ('groom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.groom')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.pet')),
            ],
        ),
    ]
